# Generated by Django 4.1 on 2023-08-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_color_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='isFeatured',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='quantity',
        ),
    ]
