# Generated by Django 4.1 on 2023-08-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productInventoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinventory')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productInventoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinventory')),
            ],
        ),
    ]
