# Generated by Django 4.1 on 2023-08-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productInventoryId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='productInventoryId',
        ),
        migrations.AddField(
            model_name='cart',
            name='productId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='productId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
